Adding Origin-Agent-Cluster
helmetjs/helmet pull request #286
Opened 2021-01-17 02:17 UTC by salesh

Related to https://github.com/helmetjs/helmet/issues/275

2021-01-17 15:53 UTC, EvanHahn requested changes
Thank you very much for doing this! It looks great but needs a few small changes.

2021-01-17 15:53 UTC, EvanHahn commented on CHANGELOG.md
> +## 4.3.2 - 2021-01-17
Could you change this heading to "unreleased"?

2021-01-17 15:53 UTC, EvanHahn commented on README.md
> +app.use(helmet.originAgentCluster());
Please remove this line because it's not enabled by default.

2021-01-17 15:53 UTC, EvanHahn commented on CHANGELOG.md
> +- `helmet.originAgentCluster`: disabled by default, set `true` enables it
Please change this to:

```suggestion
- `helmet.originAgentCluster`: a new middleware for the `Origin-Agent-Cluster` middleware, disabled by default
```

2021-01-17 15:53 UTC, EvanHahn commented on README.md
> +`helmet.originAgentCluster` The Origin-Agent-Cluster header provides a mechanism to allow web applications to isolate their origins.
```suggestion
`helmet.originAgentCluster` sets the `Origin-Agent-Cluster` header, which provides a mechanism to allow web applications to isolate their origins. Read more about it [in the spec](https://whatpr.org/html/6214/origin.html#origin-keyed-agent-clusters).
```

2021-01-17 15:53 UTC, EvanHahn commented on index.ts
> +          "Helmet no longer supports `true` as a middleware option, exception is Origin-Agent-Cluster. Remove the property from your options to fix this error."
```suggestion
          "Helmet no longer supports `true` as a middleware option, except for Origin-Agent-Cluster. Remove the property from your options to fix this error."
```

2021-01-17 16:09 UTC, salesh commented
@EvanHahn
No Evan, thank you very much for giving me the opportunity to learn and contribute - you had written really full and descriptive guide, my part is really small. I had learned a lot about how a helmet works because of this. Thank you

2021-01-17 16:52 UTC, merged

2021-01-17 17:10 UTC, EvanHahn commented
Thank you so much! I've made some small cleanups in #287 and will deploy soon.

2021-01-18 02:53 UTC, EvanHahn commented
This has been published in `helmet@4.4.0`. Thanks again!

Feel free to add yourself to [the contributors list][0], or let me know your name and URL and I can do it.

[0]: https://github.com/helmetjs/helmetjs.github.io/blob/master/contributors/index.md