Improve the Content-CSP readme with content
helmetjs/helmet pull request #291
Opened 2021-02-14 15:47 UTC by shaialon

- Explain more on client-side attacks.
- Add reference to CSP scanner.

2021-02-16 14:44 UTC, EvanHahn requested changes
Thanks for doing this! Left a few comments.

2021-02-16 14:44 UTC, EvanHahn commented on middlewares/content-security-policy/README.md
> +Content Security Policy (CSP) helps prevent unwanted content from being injected/loaded into your webpages. This can mitigate cross-site scripting (XSS) vulnerabilities, Clickjacking, formajacking, m
1. Could you make "clickjacking" lowercase?
1. Should "formajacking" be "formjacking"?
1. Could you remove "client-side injected malware"? It feels redundant with the last clause.
1. Could you remove the link?

2021-02-16 14:44 UTC, EvanHahn commented on middlewares/content-security-policy/README.md
> +This middleware does minimal validation. You should use a more sophisticated CSP validator, like [Google's CSP Evaluator](https://csp-evaluator.withgoogle.com/), or [CSP Scanner](https://cspscanner.c
Could you revert this change?

2021-02-16 14:44 UTC, EvanHahn commented on middlewares/content-security-policy/README.md
> +- [CSP Scanner - Validate and Improve a Content Security Policy](https://cspscanner.com/)
Could you just change this link to "CSP Scanner"?

2021-02-16 18:06 UTC, shaialon commented
Thanks @EvanHahn . Done 🚀

2021-02-17 00:29 UTC, EvanHahn approved these changes

2021-02-17 00:30 UTC, merged

2021-02-17 00:30 UTC, EvanHahn commented
Thanks!

2021-03-08 16:17 UTC, shaialon commented
@EvanHahn - I see this was not deployed:
https://www.npmjs.com/package/helmet-csp

I see it also has different versions, so wonder how it's setup.

2021-03-11 15:38 UTC, EvanHahn commented
Thanks for pointing this out.

Unless there's something very substantial, I don't usually deploy new versions if documentation is the only thing that's changed. The next time helmet-csp updates, I'll be sure to push these changes out.

Hope that answers your question!