types: rename `XFrameOptionsOptions` to `XFrameOptions`
helmetjs/helmet pull request #347
Opened 2022-01-13 09:26 UTC by darkgl0w

Hello.

This PR aims to :
- rename `frameguard` middleware typescript definition `XFrameOptionsOptions` to `XFrameOptions`
- deprecate typescript definition `XFrameOptionsOptions` in favor of `XFrameOptions` to avoid any breaking change for typescript users

No breaking change is introduced by this PR. ^^

2022-01-13 13:19 UTC, EvanHahn requested changes
Hmm, I'm not sure we want to do this. I agree that the name is a bit weird, though.

When I was setting this up, I thought: each middleware options type should be the header's name followed by the word "options". That means that the `Content-Security-Policy` options are `ContentSecurityPolicyOptions`.

That means that `X-Frame-Options` has the somewhat unfortunate name of `XFrameOptionsOptions`, but at least it's consistent.

What do you think about that?

2022-01-13 13:44 UTC, darkgl0w commented
Yeah, makes sense. ^^

One other way to get rid of this weird name would be to change the options typescript definitions names with the name of the middleware they apply.

E.g.: `FrameguardOptions` instead of `XFrameOptionsOptions`

And to avoid any breaking in current code we can deprecate and alias the current names with the new ones.

WDYT ?

2022-01-13 14:19 UTC, EvanHahn commented
I thought about that too. I wanted all of the middleware to correspond to one HTTP header...but maybe that's more confusing because they have different names in the top-level API?

2022-01-13 15:19 UTC, darkgl0w commented
Yes TBH I was expecting the options of each middlewares to have a name formatted like this `<MiddlewareName><Options>` (e.g: `FrameguardOptions`, `CrossOriginOpenerPolicyOptions`, `DnsPrefetchControlOptions`, ...), it kind of feels more natural.

But at the same time the current naming convention makes sense too when looking at the code (it just that one particular name that sounds a bit weird :rofl:).

I am aware that's the typical head scratching PR (:exploding_head:), and TBH I don't want to make you lose time on this just for a weird sounding option name :laughing:.
If you think it's worth the burden I will happily make all the changes to name the options after their respective middleware names. If not we can close this PR with no regrets :stuck_out_tongue:.

2022-01-13 16:38 UTC, EvanHahn commented
Are you using XFrameOptionsOptions in your app? I intended for it to be a private type, but maybe it's exported somehow unintentionally?

If they're exported, I think FrameguardOptions makes more sense as a name, but I didn't think they were exported...

2022-01-13 16:52 UTC, darkgl0w commented
Not directly, I stumbled upon this by importing `HelmetOptions` interface and then Picking `frameguard` like this:
```ts
type frameguard = Pick<HelmetOptions, 'frameguard'>;
```

2022-01-13 22:02 UTC, EvanHahn commented
Ah, I see. Are you seeing `XFrameOptionsOptions` in your IDE or something?

2022-01-14 04:07 UTC, darkgl0w commented
Yes ^^

It appears by hovering the type in question and when a typescript error is triggered with this particular type.

2022-01-14 12:54 UTC, EvanHahn commented
Ah, I see.

I think, then, we should just rename the type to `FrameguardOptions` and do the same for all of the other middlewares.

However, I want to think about it a little more. I'll let you know by Monday whether it's actually something we want to do.

2022-01-14 13:41 UTC, darkgl0w commented
Fine,
You will just have to ping me and I will update this PR to change what needs to be changed ^^

2022-01-16 20:35 UTC, EvanHahn commented
In the long term, I'd like to migrate from names like `frameguard` to names like `xFrameOptions`. I think this makes that migration a little harder, so I don't think I want to do this rename. I'm going to close this PR, but thanks for getting me to think about it.

If you (or anyone else) feels strongly about this, please let me know!

2022-01-16 20:35 UTC, closed without merging